export * from './SkeletonElements';
export { default as HomePageSkeleton } from './HomePageSkeleton';
export { default as CoursesPageSkeleton } from './CoursesPageSkeleton';
export { default as FixturesPageSkeleton } from './FixturesPageSkeleton';
export { default as GalleryPageSkeleton } from './GalleryPageSkeleton';
export { default as ResultsPageSkeleton } from './ResultsPageSkeleton';
export { default as RulesPageSkeleton } from './RulesPageSkeleton';
export { default as TeeTimesPageSkeleton } from './TeeTimesPageSkeleton';
export { default as OOMPageSkeleton } from './OOMPageSkeleton';
export { default as ClubOfficersPageSkeleton } from './ClubOfficersPageSkeleton';
export { default as FurtherResultsPageSkeleton } from './FurtherResultsPageSkeleton';